#name: Publish Docker Image
#
#on:
#  workflow_call:
#    secrets:
#      DOCKERHUB_USERNAME:
#        required: true
#      DOCKERHUB_TOKEN:
#        required: true
#
#jobs:
#  publish:
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout source code
#        uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build and push Docker image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: hlyamhtet/opom-portfolio:latest

